# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-10-18T17:01:42+00:00
#
# Hand-maintained in sync with openapi.yaml (datamodel-codegen not installed).
# When editing openapi.yaml, update the models below to match.

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class EventType(Enum):
    arrive = 'arrive'
    depart = 'depart'


class TagEventDTO(BaseModel):
    source: str = Field(..., example='sirit-510')
    reader_ip: str
    reader_serial: str | None = None
    timestamp: str = Field(
        ...,
        description='ISO8601 with milliseconds and Z',
        example='2025-10-16T11:53:32.298Z',
    )
    event_type: EventType
    tag_id: str = Field(..., description='Uppercase hex without 0x')
    session_id: Optional[int] = None
    antenna: Optional[int] = None
    rssi: Optional[int] = None
    first: Optional[str] = None
    last: Optional[str] = None


class TagEventBatchDTO(BaseModel):
    events: List[TagEventDTO]


class BatchIngestResultDTO(BaseModel):
    events_processed: int


class ParticipantDTO(BaseModel):
    tag_id: str
    laps: int
    last_pass_time: Optional[str] = None
    finish_time: Optional[str] = None
    finished: bool
    total_time_ms: Optional[int] = None
    gap_ms: Optional[int] = Field(
        None,
        description='Time gap to the leader in milliseconds when on the same lap (0 for leader; null if lapped)',
    )
    laps_behind: Optional[int] = Field(
        None, description='Number of laps behind the leader (null or 0 if on same lap)'
    )
    # F3 — result status: null (classified/racing), "dnf", "dns", "dsq".
    status: Optional[str] = None
    # F5 — advisory: laps that look missed by the reader, and the midpoint
    # timestamp of the first suspected gap (to pre-fill the manual-lap dialog).
    suspected_missed_reads: int = 0
    suspected_gap_midpoint: Optional[str] = None
    # TT/net time: first counted pass → finish (or latest) pass. The correct
    # individual time for staggered-start formats. None until 2+ passes.
    net_time_ms: Optional[int] = None
    # Rider fields — populated from RiderStore at standings time (W-010)
    bib: Optional[str] = Field(None, description='Rider bib number (null if no rider registered for this tag)')
    name: Optional[str] = Field(None, description='Rider name (null if no rider registered for this tag)')


class ClassificationDTO(BaseModel):
    count: int
    standings: List[ParticipantDTO]


class RaceDTO(BaseModel):
    """Race detail — used by GET /race (active race) and GET /races/{id}."""

    # Multi-race fields (2026-05-25). id/name are required once multi-race
    # ships; default to None for backward compat with anything still building a
    # RaceDTO without an explicit race row.
    id: Optional[str] = None
    name: Optional[str] = None
    scheduled_at: Optional[str] = None
    ended: bool = False
    ended_at: Optional[str] = None

    total_laps: int
    start_time: str
    # Explicit-start model: started_at is the timestamp the user clicked
    # "Start race". None until then. start_time (above) is the RaceState
    # construction time and is kept for backward compatibility / debugging.
    started: bool = False
    started_at: Optional[str] = None
    participants: List[ParticipantDTO]
    # F1/F2 (AUDIT-2026-07): race format + live finishing/bell state.
    finish_mode: str = "leader"
    duration_s: Optional[int] = None
    final_laps: Optional[int] = None
    finishing: bool = False
    laps_to_go: Optional[int] = None


class RaceSummaryDTO(BaseModel):
    """Race summary — used by GET /races (no participant list, lighter)."""

    id: str
    name: str
    scheduled_at: Optional[str] = None
    total_laps: int
    started: bool = False
    started_at: Optional[str] = None
    ended: bool = False
    ended_at: Optional[str] = None
    created_at: Optional[str] = None
    is_active: bool = False
    snapshot_interval_s: Optional[int] = None
    finish_mode: str = "leader"
    duration_s: Optional[int] = None
    final_laps: Optional[int] = None


class RaceListDTO(BaseModel):
    count: int
    items: List[RaceSummaryDTO]
    active_race_id: Optional[str] = None


class RaceCreateDTO(BaseModel):
    """Body of POST /races."""

    name: str = Field(..., min_length=1, max_length=200)
    scheduled_at: Optional[str] = None  # ISO 8601 datetime; nullable
    total_laps: int = Field(default=5, ge=1, le=999)
    snapshot_interval_s: Optional[int] = Field(
        default=None, ge=0, le=3600,
        description=(
            "Seconds between automatic snapshots (CSV + DB) for this race. "
            "None or 0 disables snapshots. Capped at 3600 (1 h)."
        ),
    )
    finish_mode: str = Field(
        default="leader",
        pattern="^(leader|per_rider)$",
        description=(
            "'leader' (criterium: leader crossing the line finishes the race, "
            "others flagged off at their next pass) or 'per_rider'."
        ),
    )
    duration_s: Optional[int] = Field(
        default=None, ge=1, le=86400,
        description="Time-based race duration in seconds. Requires final_laps.",
    )
    final_laps: Optional[int] = Field(
        default=None, ge=0, le=99,
        description="Laps to go once the timer expires (bell lap). Requires duration_s.",
    )


class RaceUpdateDTO(BaseModel):
    """Body of PATCH /races/{id} — every field optional, only set ones apply."""

    name: Optional[str] = Field(default=None, min_length=1, max_length=200)
    scheduled_at: Optional[str] = None
    total_laps: Optional[int] = Field(default=None, ge=1, le=999)
    snapshot_interval_s: Optional[int] = Field(default=None, ge=0, le=3600)
    finish_mode: Optional[str] = Field(default=None, pattern="^(leader|per_rider)$")
    duration_s: Optional[int] = Field(default=None, ge=0, le=86400)
    final_laps: Optional[int] = Field(default=None, ge=0, le=99)


# ---------------------------------------------------------------------------
# Rider DTOs (W-010) — hand-written to match openapi.yaml RiderDTO /
# RiderCreateDTO schemas.
# ---------------------------------------------------------------------------

class RiderDTO(BaseModel):
    """Rider as returned by the API (includes server-assigned created_at)."""

    tag_id: str = Field(..., description='RFID tag id (uppercase hex, primary key)')
    bib: str = Field(..., description='Bib number (stored as string to preserve leading zeros)')
    name: str = Field(..., description='Rider display name')
    created_at: datetime = Field(..., description='UTC timestamp when the rider was first registered')
    status: Optional[str] = Field(None, description='Result status: null, "dnf", "dns", "dsq"')
    verein: str = Field('', description='Club (SRB official-result export)')
    uci_id: str = Field('', description='UCI ID (SRB official-result export)')
    races_updated: Optional[int] = Field(
        None,
        description='Only set when the request had all_races=true: number of '
                    'race rows (across ALL races) that were updated.',
    )


class RiderCreateDTO(BaseModel):
    """Payload accepted by POST /riders."""

    tag_id: str = Field(..., description='RFID tag id (uppercase hex)')
    bib: str = Field(..., description='Bib number')
    name: str = Field(..., description='Rider display name')
    verein: str = Field('', description='Club — empty keeps an existing value')
    uci_id: str = Field('', description='UCI ID — empty keeps an existing value')
    all_races: bool = Field(
        default=False,
        description='Also update bib/name for this tag in every OTHER race '
                    'where it is registered (day model: one tag + number per '
                    'person). Update-only — never inserts into other races.',
    )


class RiderStatusDTO(BaseModel):
    """Body of PATCH /riders/{tag_id}/status. status=null clears it (F3)."""

    status: Optional[str] = Field(
        default=None,
        description='Result status: null (classified), "dnf", "dns", or "dsq"',
    )


class RidersListDTO(BaseModel):
    """Response for GET /riders."""

    count: int
    items: List[RiderDTO]


class RecentReadDTO(BaseModel):
    """Single entry in the recent-unknown-tags ring buffer."""

    tag_id: str
    timestamp: str
    antenna: Optional[int] = None
    rssi: Optional[int] = None


class RecentReadsListDTO(BaseModel):
    """Response for GET /riders/recent-reads."""

    count: int
    items: List[RecentReadDTO]


# ---------------------------------------------------------------------------
# Manual lap correction (Feature: +1/-1 lap for a rider, optional manual ts).
# Triggered by the operator when the reader miscounts (mis-read, sleeper tag,
# weak antenna). The synthetic lap is persisted to tag_events with
# reader_serial="MANUAL" so it can be distinguished from real reader events
# in audits / replay.
# ---------------------------------------------------------------------------

class ManualLapAddDTO(BaseModel):
    """Payload for POST /riders/{tag_id}/laps."""

    timestamp: Optional[str] = Field(
        default=None,
        description=(
            "ISO-8601 UTC timestamp for the synthetic lap pass. If omitted, "
            "the server uses its current UTC time. Operator can supply a past "
            "timestamp (e.g. the moment the rider crossed the line) when the "
            "click happens later than the actual pass."
        ),
    )


class ManualLapResultDTO(BaseModel):
    """Response for manual lap add/remove."""

    tag_id: str
    laps: int
    last_pass_time: Optional[str] = None
    finished: bool = False
    finish_time: Optional[str] = None
    total_time_ms: Optional[int] = None
